# Generated by Django 6.0.1 on 2026-01-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearance',
            options={'ordering': ['issue__publishing_date']},
        ),
        migrations.AlterModelOptions(
            name='woman',
            options={'verbose_name_plural': 'Women'},
        ),
    ]
