# Generated by Django 6.0.1 on 2026-01-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appearance_options_alter_woman_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='core.issue')),
            ],
        ),
    ]
